In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os, sys
sys.path.append('/content/drive/MyDrive/DCDP/mean')

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import random

import itertools

import time
import bisect

import pandas as pd

import statsmodels.api as sm
from sklearn import linear_model

from warnings import simplefilter
from sklearn.exceptions import ConvergenceWarning
simplefilter("ignore", category=ConvergenceWarning)

In [ ]:
def generate_data_mean(n, T, theta):
    p = len(theta[0])
    y_train = np.concatenate([np.random.multivariate_normal(theta[i], np.eye(p), n[i]) for i in range(T)])
    y_train_joint = y_train.reshape((-1, p))
    nt = len(y_train_joint)
    
    return nt, y_train_joint

In [ ]:
T = 4
Delta = 50
p = 20
theta = np.zeros((T, p))
for t in range(T):
    theta[t, 5 * t: 5 * (t + 1)] = 5

diff = np.zeros(T - 1)
for t in range(1, T):
    diff[t - 1] = np.sum(np.abs(theta[t] - theta[t - 1])**2)**0.5
print(diff)

np.random.seed(0)

nt = Delta * T
B = 100
Y_train_list = np.zeros((B, nt, p))
Y_test_list = np.zeros((B, nt, p))
cp_truth_list = np.zeros((B, T - 1))
for b in range(B):
    n = np.array([Delta] * T) + np.random.uniform(-15, 15, T).astype(int)
    n[-1] = nt - np.sum(n[:-1])
    cp_truth = np.cumsum(n)[:T-1]
    nt, Y_train = generate_data_mean(n, T, theta)
    nt, Y_test = generate_data_mean(n, T, theta)
    Y_train_list[b] = Y_train
    Y_test_list[b] = Y_test
    cp_truth_list[b] = cp_truth

path = '/content/drive/MyDrive/DCDP/mean/'
with open(path + 'data_n' + str(nt) + '_p' + str(p) + '_Delta' + str(Delta) + '_K' + str(T - 1) + '_kappa' + str(int(np.mean(diff) * 100)) + '.npz', 'wb') as f:
    np.savez(f, Y_train_list = Y_train_list, Y_test_list = Y_test_list, cp_truth_list = cp_truth_list, theta = theta)

[15.8113883 15.8113883 15.8113883]


In [ ]:
T = 4
Delta = 50
p = 20
theta = np.zeros((T, p))
for t in range(T):
    theta[t, 5 * t: 5 * (t + 1)] = 1

diff = np.zeros(T - 1)
for t in range(1, T):
    diff[t - 1] = np.sum(np.abs(theta[t] - theta[t - 1])**2)**0.5
print(diff)

np.random.seed(0)

nt = Delta * T
B = 100
Y_train_list = np.zeros((B, nt, p))
Y_test_list = np.zeros((B, nt, p))
cp_truth_list = np.zeros((B, T - 1))
for b in range(B):
    n = np.array([Delta] * T) + np.random.uniform(-15, 15, T).astype(int)
    n[-1] = nt - np.sum(n[:-1])
    cp_truth = np.cumsum(n)[:T-1]
    nt, Y_train = generate_data_mean(n, T, theta)
    nt, Y_test = generate_data_mean(n, T, theta)
    Y_train_list[b] = Y_train
    Y_test_list[b] = Y_test
    cp_truth_list[b] = cp_truth

path = '/content/drive/MyDrive/DCDP/mean/'
with open(path + 'data_n' + str(nt) + '_p' + str(p) + '_Delta' + str(Delta) + '_K' + str(T - 1) + '_kappa' + str(int(np.mean(diff) * 100)) + '.npz', 'wb') as f:
    np.savez(f, Y_train_list = Y_train_list, Y_test_list = Y_test_list, cp_truth_list = cp_truth_list, theta = theta)

[3.16227766 3.16227766 3.16227766]


In [ ]:
T = 4
Delta = 50
p = 20
theta = np.zeros((T, p))
for t in range(T):
    theta[t, 5 * t: 5 * (t + 1)] = 0.5

diff = np.zeros(T - 1)
for t in range(1, T):
    diff[t - 1] = np.sum(np.abs(theta[t] - theta[t - 1])**2)**0.5
print(diff)

np.random.seed(0)

nt = Delta * T
B = 100
Y_train_list = np.zeros((B, nt, p))
Y_test_list = np.zeros((B, nt, p))
cp_truth_list = np.zeros((B, T - 1))
for b in range(B):
    n = np.array([Delta] * T) + np.random.uniform(-15, 15, T).astype(int)
    n[-1] = nt - np.sum(n[:-1])
    cp_truth = np.cumsum(n)[:T-1]
    nt, Y_train = generate_data_mean(n, T, theta)
    nt, Y_test = generate_data_mean(n, T, theta)
    Y_train_list[b] = Y_train
    Y_test_list[b] = Y_test
    cp_truth_list[b] = cp_truth

path = '/content/drive/MyDrive/DCDP/mean/'
with open(path + 'data_n' + str(nt) + '_p' + str(p) + '_Delta' + str(Delta) + '_K' + str(T - 1) + '_kappa' + str(int(np.mean(diff) * 100)) + '.npz', 'wb') as f:
    np.savez(f, Y_train_list = Y_train_list, Y_test_list = Y_test_list, cp_truth_list = cp_truth_list, theta = theta)

[1.58113883 1.58113883 1.58113883]


In [ ]:
T = 4
Delta = 50
p = 100
theta = np.zeros((T, p))
for t in range(T):
    theta[t, 5 * t: 5 * (t + 1)] = 5

diff = np.zeros(T - 1)
for t in range(1, T):
    diff[t - 1] = np.sum(np.abs(theta[t] - theta[t - 1])**2)**0.5
print(diff)

np.random.seed(0)

nt = Delta * T
B = 100
Y_train_list = np.zeros((B, nt, p))
Y_test_list = np.zeros((B, nt, p))
cp_truth_list = np.zeros((B, T - 1))
for b in range(B):
    n = np.array([Delta] * T) + np.random.uniform(-15, 15, T).astype(int)
    n[-1] = nt - np.sum(n[:-1])
    cp_truth = np.cumsum(n)[:T-1]
    nt, Y_train = generate_data_mean(n, T, theta)
    nt, Y_test = generate_data_mean(n, T, theta)
    Y_train_list[b] = Y_train
    Y_test_list[b] = Y_test
    cp_truth_list[b] = cp_truth

path = '/content/drive/MyDrive/DCDP/mean/'
with open(path + 'data_n' + str(nt) + '_p' + str(p) + '_Delta' + str(Delta) + '_K' + str(T - 1) + '_kappa' + str(int(np.mean(diff) * 100)) + '.npz', 'wb') as f:
    np.savez(f, Y_train_list = Y_train_list, Y_test_list = Y_test_list, cp_truth_list = cp_truth_list, theta = theta)

[15.8113883 15.8113883 15.8113883]


In [ ]:
a = np.array([Delta] * T) + np.random.uniform(-150, 150, T).astype(int)
a[-1] = nt - np.sum(a[:-1])
np.cumsum(a)

array([ 355,  955, 1430, 2000])

In [ ]:
cp_truth

array([ 500, 1000, 1500])

In [ ]:
T = 4
Delta = 50
p = 100
theta = np.zeros((T, p))
for t in range(T):
    theta[t, 5 * t: 5 * (t + 1)] = 1

diff = np.zeros(T - 1)
for t in range(1, T):
    diff[t - 1] = np.sum(np.abs(theta[t] - theta[t - 1])**2)**0.5
print(diff)

np.random.seed(0)

nt = Delta * T
B = 100
Y_train_list = np.zeros((B, nt, p))
Y_test_list = np.zeros((B, nt, p))
cp_truth_list = np.zeros((B, T - 1))
for b in range(B):
    n = np.array([Delta] * T) + np.random.uniform(-15, 15, T).astype(int)
    n[-1] = nt - np.sum(n[:-1])
    cp_truth = np.cumsum(n)[:T-1]
    nt, Y_train = generate_data_mean(n, T, theta)
    nt, Y_test = generate_data_mean(n, T, theta)
    Y_train_list[b] = Y_train
    Y_test_list[b] = Y_test
    cp_truth_list[b] = cp_truth

path = '/content/drive/MyDrive/DCDP/mean/'
with open(path + 'data_n' + str(nt) + '_p' + str(p) + '_Delta' + str(Delta) + '_K' + str(T - 1) + '_kappa' + str(int(np.mean(diff) * 100)) + '.npz', 'wb') as f:
    np.savez(f, Y_train_list = Y_train_list, Y_test_list = Y_test_list, cp_truth_list = cp_truth_list, theta = theta)

[3.16227766 3.16227766 3.16227766]


In [ ]:
Y_train_list.shape

(100, 2000, 100)

In [ ]:
T = 4
Delta = 200
p = 100
theta = np.zeros((T, p))
for t in range(T):
    theta[t, 5 * t: 5 * (t + 1)] = 0.5

diff = np.zeros(T - 1)
for t in range(1, T):
    diff[t - 1] = np.sum(np.abs(theta[t] - theta[t - 1])**2)**0.5
print(diff)

np.random.seed(0)

nt = Delta * T
B = 100
Y_train_list = np.zeros((B, nt, p))
Y_test_list = np.zeros((B, nt, p))
cp_truth_list = np.zeros((B, T - 1))
for b in range(B):
    n = np.array([Delta] * T) + np.random.uniform(-60, 60, T).astype(int)
    n[-1] = nt - np.sum(n[:-1])
    cp_truth = np.cumsum(n)[:T-1]
    nt, Y_train = generate_data_mean(n, T, theta)
    nt, Y_test = generate_data_mean(n, T, theta)
    Y_train_list[b] = Y_train
    Y_test_list[b] = Y_test
    cp_truth_list[b] = cp_truth

path = '/content/drive/MyDrive/DCDP/mean/'
with open(path + 'data_n' + str(nt) + '_p' + str(p) + '_Delta' + str(Delta) + '_K' + str(T - 1) + '_kappa' + str(int(np.mean(diff) * 100)) + '.npz', 'wb') as f:
    np.savez(f, Y_train_list = Y_train_list, Y_test_list = Y_test_list, cp_truth_list = cp_truth_list, theta = theta)

[1.58113883 1.58113883 1.58113883]
